from app.models import db, Course


def seed_courses():
  courses = {}
  courses[1] = Course(courseName="The Stadium Course at TPC Scottsdale", address="17020 North Hayden Rd., Scottsdale, Arizona, 85255", location="33.64062,-111.90887", description="Set in the Sonoran Desert and surrounded by the majestic McDowell Mountains, the Tournament Players Club of Scottsdale, a 36-hole daily fee public golf course owned and operated by the PGA TOUR represents the standards of excellence in golf operations world wide. The design team of Tom Weiskopf and Jay Morrish created a masterful blend of challenge and playability between the Stadium Course and the Champions Course, two uniquely different golfing venues. From the first moment you arrive at TPC Scottsdale, the home of the PGA TOUR's Waste Management Phoenix Open, you will experience first hand what sets TPC Network Clubs apart from all other golf facilities. TPC Scottsdale, a PGA TOUR Facility, embodies the standards of excellence in golf operations world wide.", imageURL="https://x8t5x9a4.map2.ssl.hwcdn.net/app/courses/image/preview/104982.jpg")
  courses[2] = Course(courseName="Ak-Chin Southern Dunes Golf Club", address="48456 West, AZ-238, Maricopa, AZ 85139", location="33.07906541327542, -112.08481011706853", description="Opened in 2002, Ak-Chin Southern Dunes has been widely recognized as one of the best layouts in the state. The Fred Couples/Schmidt-Curley design has tested some of the best players in the world, and is now ready for you. Perfect course conditions coupled with a relaxed and welcoming environment makes for one of the most unique and enjoyable golf experiences in the Valley. With rolling hills, native grasses, and tees that start at 5300 yards and can reach over 7500 yards, Ak-Chin Southern Dunes Golf Club is a unique golf experience that will challenge the most accomplished golfer while still accommodating the novice.", imageURL="https://x8t5x9a4.map2.ssl.hwcdn.net/app/courses/image/preview/86637.jpg")
  courses[3] = Course(courseName="TPC Scottsdale - Champions Course", address="8243 E Bell Rd, Scottsdale, AZ 85260", location="33.63876965119996, -111.90559245901437", description="Set in the Sonoran Desert and surrounded by the majestic McDowell Mountains, the Tournament Players Club of Scottsdale, a 36-hole daily fee public golf course owned and operated by the PGA TOUR represents the standards of excellence in golf operations world wide. The design team of Tom Weiskopf and Jay Morrish created a masterful blend of challenge and playability between the Stadium Course and the Champions Course, two uniquely different golfing venues. From the first moment you arrive at TPC Scottsdale, the home of the PGA TOUR's Waste Management Phoenix Open, you will experience first hand what sets TPC Network Clubs apart from all other golf facilities. TPC Scottsdale, a PGA TOUR Facility, embodies the standards of excellence in golf operations world wide.", imageURL="https://x8t5x9a4.map2.ssl.hwcdn.net/app/courses/image/preview/3245.jpg")
  courses[4] = Course(courseName="TPC Sawgrass - The Players Stadium", address="110 Championship Way, Ponte Vedra Beach, , 32082", location="30.19923835485517, -81.39482127323625", description="Not far from Ponte Vedra Beach, TPC Sawgrass - The PLAYERS Stadium offers terrific views and challenging play for golfers at every skill level. Well-groomed fairways and greens keep TPC Sawgrass - The PLAYERS Stadium difficult yet friendly, and the staff can offer tips and tricks for playing your best round. TPC Sawgrass - The PLAYERS Stadium is a terrific choice for your regular rounds of golf or a new destination for you and friends when visiting Ponte Vedra Beach.", imageURL="https://x8t5x9a4.map2.ssl.hwcdn.net/app/courses/image/preview/2868.jpg")
  courses[5] = Course(courseName="Troon North Golf Club", address="10320 E Dynamite Blvd., Scottsdale, Arizona, 85255", location="33.746484386463806, -111.85878261549034", description="Troon North Golf Club stands as the hallmark of the desert golf experience, stretching through the natural ravines and foothills in the high Sonoran desert in the shadows of Pinnacle Peak. The challenge, visual sensation, and special ambiance of Troon North sets the standards by which all others are measured and the immaculately groomed golf course and exceptional level of customer service create the renowned Troon Golf Experience. Troon North’s Monument and Pinnacle courses consistently rank at the top of every golfer’s must-play list, and as of October 2007 golfers in search of the ultimate golf experience are returning to Troon North Golf Club to play Tom Weiskopf’s true vision. New course renovations by original designer and British Open Champion, Tom Weiskopf, have created two new layouts with improved playability! Troon North Golf Club also offers food and beverage services to our guests while providing one of the most scenic backdrops in the State of Arizona. The Grille at Troon North overlooks the 18th hole of the Monument golf course which is surrounded by beautiful desert landscape and custom built homes. The Grille at Troon North is open for breakfast seven days a week, and provides lunch and dinner Monday through Saturday. The Grille is open to golfers and non-golfers for an unparalleled dining experience. Troon North also offers numerous catering and banquet options.", imageURL="https://x8t5x9a4.map2.ssl.hwcdn.net/app/courses/image/preview/3612.jpg")
  courses[6] = Course(courseName="Kokopelli Golf Club", address="1800 W. Guadalupe Road, Gilbert, Arizona, 85233", location="33.36643609108965, -111.82947464433425", description="This spectacular Bill Phillips-designed course is located 20 minutes from Sky Harbor Airport. It features impressive mounding, rolling fairways and fast breaking, challenging greens, highlighted by seven serpentine lakes and exceptional views.", imageURL="https://x8t5x9a4.map2.ssl.hwcdn.net/app/courses/image/preview/104830.jpg")
  courses[7] = Course(courseName="Whirlwind Golf Club", address="5692 North Loop Road, Chandler, Arizona, 85226", location="33.26986856907225, -111.99039530200756", description="Whirlwind Golf Club has established itself as a premier golf destination for Arizonans as well as travelers from around the globe. The facility features 36 perfectly manicured holes draped over 242 acres of exquisite desert landscape. The property’s signature wild, roaming horses and other desert wildlife enjoy the peacefulness of Whirlwind’s unspoiled habitat. Despite the short 12-mile drive from Phoenix’s Sky Harbor International Airport, guests of Whirlwind indulge themselves in the picturesque golf environment and the tranquility of a location so seemingly distant from the commotion of everyday life.", imageURL="https://x8t5x9a4.map2.ssl.hwcdn.net/app/courses/image/preview/3694.jpg")
  courses[8] = Course(courseName="Quintero Golf Club", address="16752 West State Route 74, Peoria, Arizona, 85383", location="33.83956299936741, -112.42316743083049", description="Accessible yet secluded, this exclusive private golf club is located less than one hour northwest of Phoenix Sky Harbor airport, in the high Sonoran desert near Lake Pleasant in the Hieroglyphic Mountains. First and foremost, Quintero Golf Club is about great golf. Unlike many other newer private clubs, there is no real estate requirement to join the club, and residences will be very limited: only 283 on a property over 828 acres in size. The first golf course, the 7208-yard Founders Course, was designed by esteemed architect Rees Jones and includes an extensive practice facility. Jones's creation has been named one of America's Top 100 modern golf courses by Golfweek Magazine since 2002. Located at an elevation between 1986 and 2670 feet, the entire property is surrounded by Federal lands managed by the Bureau of Land Management, adding to the feeling of privacy. In addition to the 18 holes of spectacular mountain golf and golf clubhouse, the property will include a fitness and vitality center, a putting course, tennis courts, swimming pool, and hiking trails. The facility takes full advantage of the sweeping desert landscape with significant elevation changes and lush collections of native saguaro, ocotillo, ironwood, palo verde, and acacia trees. Great care has been taken to maintain the natural setting, making the course look like it has been a part of the landscape for many years. The gated private Phoenix golf community provides the feeling of a secluded private retreat that is a comfortable home away from home.", imageURL="https://x8t5x9a4.map2.ssl.hwcdn.net/app/courses/image/preview/74442.jpg")
  courses[9] = Course(courseName="McDowell Mountain Golf Club", address="10690 E Sheena Dr, Scottsdale, Arizona, 85255", location="33.61686764526727, -111.85292982383619", description="McDowell Mountain Golf Club (formerly the Sanctuary Golf Course) re-opened with a bang when PGA Tour great and former Arizona State Sun Devil, Phil Mickelson struck the first tee shot and took part in the ribbon cutting ceremony with Scottsdale Mayor Jim Lane in October. Mickelson, Honorable Mayor Lane, Steve Loy and course architect Randy Heckenkemper were on hand to unveil the newly enhanced McDowell Mountain Golf Club. Located in the heart of Scottsdale on natural desert landscape owned jointly by the Federal Bureau of Reclamation and the City of Scottsdale, McDowell Mountain Golf Club is certainly creating a buzz in the Scottsdale golf scene. In spring of 2011, Phil Mickelson and Steve Loy acquired the operating rights to McDowell Mountain Golf Club, and this summer with Scottsdale-based OB Sports, took on a significant golf course enhancement and renovation that was designed to make the course more challenging for the better players, while at the same time making the course more forgiving, enjoyable and fun for beginning golfers, families and players of all abilities. Course revisions were overseen by golf course architect Randy Heckenkemper and included widening of the playing corridors, the reshaping of a number of fairways, several new teeing areas, additional strategic waste bunkers, and more! More than 20,000 cubic yards of reshaping was done throughout the course to improve playability, widen the playing corridors, and to create a more enjoyable overall experience.", imageURL="https://x8t5x9a4.map2.ssl.hwcdn.net/app/courses/image/preview/891.jpg")
  courses[10] = Course(courseName="Wildfire Golf Club - Faldo Course", address="5350 E Marriott Dr, Phoenix, Arizona, 85054-6147", location="33.68386763588233, -111.96622110199844", description="Faldo Championship Course is the newest 18-hole course located directly adjacent to the Palmer Course. It has a par 71 layout on a 174-acre site. It offers a slight variation from typical Sonoran Desert-theme courses, with generous fairways in a spectacular setting.", imageURL="https://x8t5x9a4.map2.ssl.hwcdn.net/app/courses/image/preview/111188.jpg")
  

  for i in range(1,11):
    db.session.add(courses[i])
  db.session.commit()


def undo_courses():
  db.session.execute('TRUNCATE courses;')
  db.session.commit()
